#!/bin/python
import lftools as lf
import numpy as np
import fileinput
import os, sys
import pdb
import StringIO

def main(*args):
	fdict={f:lf.openseries(f) for f in args}

	lines=[]
	averages=[]
	mondis=[]
	for f in sorted(fdict.keys()):
		for asc in sorted(fdict[f][2].keys()):
			mondis.append(lf.get_monitor_diode_value(asc))
			lines.append("{} {} {} {} {} {} {}".format(f, asc, fdict[f][2][asc]['T'], fdict[f][2][asc]['MeanCR'], "NaN", "NaN", mondis[-1]))
		Ts=[fdict[f][2][asc]['T'] for asc in fdict[f][2]]
		MeanCRs=[fdict[f][2][asc]['MeanCR'] for asc in fdict[f][2]]
		aveT=np.average(Ts)
		stdT=np.std(Ts)
		aveCR=np.average(MeanCRs)
		stdCR=np.std(MeanCRs)
		avemondi=np.average(mondis)
		mondis=[]
		averages.append("{} {} {} {} {} {} {}".format(f, "AVERAGE", aveT, aveCR, stdT, stdCR, avemondi))

	# VSTACK THE ARRAY
	linesarray=np.hstack((lines, averages))
	header="Generated by DLS-tab-CRs.py \n"
	header+=" ".join(("folder","filename","MeanT", "MeanCR", "StderT", "StderCR", "Monitor_diode")) + "\n"

	s=StringIO.StringIO()
	np.savetxt(s, linesarray, header=header, fmt="%s")

	sys.stdout.write(s.getvalue())

if __name__=='__main__':
	# no roomfor options at the moment. but maybe in the future
	args=[]
	for line in fileinput.input():
		files=(line.split(' '))
		for i in files: args.append(i.replace('\n',''))

	main(*args)

