# !/bin/python2.7
#
# 2015.04.28 Aljosha Filippov
#
# tools all good for fun and kicks

from scipy import optimize
import sys


import scipy.integrate as itg
import numpy as np
import matplotlib.pyplot as pp
import scipy.special as spc
import glob as gl
import re


def import_ts(file_name):
  """ import_ts(file_name) takes string file_name and gives out [data, header] with data a Nrow*Ncolumn list
    and header a Ncolumn list with header names
  2015.04.28 // Aljosha Filippov
  reads text file from file_name, untill "# time" is encountered (as in a column header from YAST output).
  From then, data from all columns are returned as a two-dimensional list with  """
  
  print file_name
  
  first_line_found=False
  time_points=0
  data=[[]]
  
  # print "main here"
  # print argv[1]
  
  with open(file_name) as f:
    N_columns=None
    for line in f:
      # print line    
      words=line.split()
      # print words
      if not ('----' in line):
        if (first_line_found and ('#' != words[0][0])):
          to_append=[float(i) for i in words]
          data.append(to_append[0:N_columns])
          time_points += 1
      if "".join(words[0:2]) in ["#time", "#dt", "#weed=1", "#q"]:
        first_line_found=True
        N_columns=len(words)-1                                   # this excludes the hashtag comment
        data[0]=words[1:N_columns+1]                            # should skip the hashtag comment, as we start from one
        header=data[0]
        data[0]=[[0] for i in range(1,N_columns+1)]
  data=data[1:len(data)]
  return [data, header]
# } end def main(argv)

def construct_ts(file_as_list):
    """
    Takes output from out_data as a string, splits it into lines, and constructs a table from the results
    """
    data=[  ]
    lines=file_as_list.split("\n")
    for l in lines[2:-6]: # explicitly assuming all files generated by out_data to be identical
        data.append(map(float,l.split()))
    #
    return np.array(data)
#

def fastts(file_name):
  return np.array(import_ts(file_name)[0])

def write_ser(file_name, data, header="# time generated by tools.write_ser"):
  # 2015.04.28 // Aljosha Filippov
  # Writes dataseries from two-dimensional list data with column descriptions from one-dimensional list header into a text file to file_name.
  
  str_header="# "
  for i in header: 
    str_header += str(i) + " "
  
  with open(file_name, 'w') as f:
    f.write(str_header[0:len(str_header)-1] + "\n")  
    
    for i in data:
      new_line = ""
      for j in i:
        new_line += str(j) + " "
      # } end for j
      new_line = new_line[0:len(new_line)-1]
      f.write(new_line + "\n")
    # } end for i
    
  # } with
  print "Wrote to filename " + file_name 


def index_nearest(array, value):
    idx = (np.abs(array-value)).argmin()
    return idx
idx=index_nearest

def index_first(array, value, tolerance=0.001):
    idcs=np.where(np.abs((array-value))<tolerance)
    print idcs
    return idcs[0][0]
idf=index_first

def merge_lin_log(lin_series, log_series, merge_at=10, overlap=0):
    """
    2015.05.06 // Aljosha filippov
    
    merges time series on a linear and log time scale by combining and re-sorting 
    the two datasets
    
    merge_lin_log(lin_series, log_series, merge_at, overlap) returns merged_series
    
    lin_series and log_series are Nxc numpy arrays to store the linear and logarithmically sampled time series, respectively. 
    merge_at and overlap are numerals, use merge_at to supply a time point from which on the linear time will be taken,
    use overlap to specify the fraction of logarithmic samples after merge_at that will overlap with the linear samples.
    log_series will be put in front of lin_series, and it is assumed that log_series is the shorter of the two.
    
    The following is a script to test merge_lin_log:
    
    path_lin="/tmpmnt/home/users/aljosha/DATA/ff01-2015.04.29/T1.00-isf-linscale/isf_100.159q0.27.dat"
    path_log="/tmpmnt/home/users/aljosha/DATA/ff01-2015.04.29/T1.00-isf-logscale/isf_100.q0.27.dat"
    data_lin=np.array(tools.import_ts(path_lin)[0])
    data_log=np.array(tools.import_ts(path_log)[0])
    
    data_lin_log=merge_lin_log(data_lin, data_log, merge_at=0.1, overlap=10)   # change it to accomodate the shape of the data
    
    pp.figure()
    pp.plot(data_lin_log[:,0], data_lin_log[:,3], 'x')
    pp.xscale('log')
    pp.ylim(-0.05,1.05)
    pp.show()


    """
    
    # find the point closest to merge_at    
    if len(lin_series)<overlap*len(log_series): print "Currently, this will not work. Expect random exceptions anytime soon."

    lin_merge_at=index_nearest(lin_series[:,0], merge_at)
    log_merge_at=index_nearest(log_series[:,0], merge_at)   
    
    # the logarithmically sampled series are taken first, and determine the extent of overlap
    idx_last_log=int(np.floor((1+overlap)*log_merge_at))
    idx_first_lin=lin_merge_at

    # truncate the numpy arrays
    log_series=log_series[0:idx_last_log]
    lin_series=lin_series[idx_first_lin:len(lin_series)]
    
    # merge the time series, arranged by time (d'oh)    
    all_series=np.concatenate((log_series, lin_series), axis=0)
    all_series=all_series[np.argsort(all_series[:,0])]
    
    return all_series
    
## test run before commiting it it to tools.py


# -*- coding: utf-8 -*-




# first try
#def rouse_q_027 (p, ff, t):
#    # experimental time shift parameter is experimental
#    D=p[0]
#    fitfunc=exp(-(t)*D*0.27**2)
#    errfunc=ff-fitfunc
#    return errfunc
    


def ff_rouse_short_q (p, ff, t, q):
    D=p[0]
    fitfunc=np.exp(-t*D*q**2)
    errfunc=ff-fitfunc
    return errfunc

    
def ff_fit_Rouse_small_q (time, ff, q, Dtest=0.0005):
    """
    Created on Wed May  6 15:00:47 2015
    
    @author: aljosha
    
    Fits the short-q solution of the Rouse prediction for the dynamic form factor,
    which is defined by F(q,t)/F(q)=exp(-Dq^2t) by finding diffusion coefficient D
    that minimizes the differences between given form factor and the one predicted
    by the short-q approximation derived from the Rouse model. 
    
    ff_fit_Rouse_small_q (time, ff, q, Dtest=0.2) takes a time series with the time as time, 
    form factor as ff, the wave vector over which ff was analyzed as q and a guess for the
    diffusion coefficient as D. It returns the optimal D for the given data set along with
    a boolean success.
    
    See the original script or the commented lines for a test routine.
    
    """

    D,success = optimize.leastsq(ff_rouse_short_q, [Dtest], args=(ff, time, q))
    return D, success

def r2n_curve (p, r2n, x, rho):
    r2n_model=p[0]**2*(1-1.2*(np.sqrt(24/np.pi**3)*(1/(rho*p[0]**3))*(1/np.sqrt(x)) ))        
    print p

    errfunc=r2n-r2n_model    
    return errfunc
    
def r2n_naked (s, p, rho):
    """
    r2n_naked (s, p, rho)
    """
    
    r2n_model=p[0]**2*(1-1.2*(np.sqrt(24/np.pi**3)*(1/(rho*p[0]**3))*(1/np.sqrt(s)) ))        
    return r2n_model

def ff_fit_r2n (s, r2n, rho, ptest=[1.2]):
    """
    Created on Wed May  6 15:00:47 2015
    
    ff_fit_r2n (s, r2n, rho, ptest=[1.2])

    @author: aljosha
    
    """
    
    popt= optimize.leastsq(r2n_curve, ptest[:], args=(r2n, s, rho))
    be=popt[0]
    return be



def ff_biexp (p, ff, t, q):

    """
    ff_biexp (p, ff, t, q)
    """


    print p
    D1=p[0]
    D2=p[1]
    
    fitfunc=np.exp(-t*D1*q**2) + np.exp(-t*D2*q**2)
    errfunc=ff-fitfunc
    
    return errfunc



def ff_biexp_naked (p, t, q):
    fitfunc=np.exp(-t*p[0]*q**2) + np.exp(-t*p[1]*q**2)
    return fitfunc

def ff_fit_biexp (time, ff, q, Dtest=[0.002,0.02]):
    """
    Created on Wed May  6 15:00:47 2015
    
    @author: aljosha
    
    Fits the time series (time, ff) to a decay in two exponents. This is inspired by the short-q
    asymptote of the Rouse solution for the decorrelation of the dynamic form factor.
    
    ff_fit_biexp (time, ff, q, Dtest=0.2) takes a time series with the time as time, 
    form factor as ff, the wave vector over which ff was analyzed as q and a guess for the
    diffusion coefficient as D. It returns optimal D1 and D2 for the given data set along with
    a boolean success.
    
    See the original script or the commented lines for a test routine.
    
    """
    
    popt= optimize.leastsq(ff_biexp, Dtest[:], args=(ff, time, q))
    D1, D2 = popt[0]
    
    return D1, D2

def large_angle_Rouse_scaling(time=np.logspace(-6, 4, num=100)):
    def integrand_two(u, x):
        uxdivsq=u*x**(-0.5)
        h_of_u_val=2/np.pi*(np.exp(-uxdivsq**2/4)*np.sqrt(np.pi)+(np.pi/2*uxdivsq)*(-1 + spc.erf(uxdivsq/2)))
        #h_of_u_val=h_of_u_analytical(uxdivsq)
        return np.exp(-u-x**0.5*h_of_u_val)
    
    def f_of_x(x):
        ding=itg.quad(integrand_two, 0, np.inf, args=x)
        # print "an x-value of " + str(x) + " gives f " + str(ding) + " with error " + str(fout)
        sys.stdout.write('.')
        return ding[0]
        
    print "integrating"    
    
    values=np.zeros((len(time),1))
    values[:,0] = [ f_of_x(time[i]) for i in range(0,len(time)) ]
    
    return values[:,0]
    
    # tools.write_ser("/tmpmnt/home/users/aljosha/rouse_prediction_dsf_2.out", values, ["# time","f(x)"])

def plot_large_angle_Rouse_scaling(time=np.logspace(-6, 4, num=100)):
    pp.plot(time, large_angle_Rouse_scaling(time), "--", label="Rouse prediction", lw=1.5)
    
    
# Test routine
#path_lin="/tmpmnt/home/users/aljosha/DATA/ff01-2015.04.29/T1.00-isf-linscale/isf_100.159q0.27.dat"
#path_log="/tmpmnt/home/users/aljosha/DATA/ff01-2015.04.29/T1.00-isf-logscale/isf_100.q0.27.dat"
#data_lin=array(tools.import_ts(path_lin)[0])
#data_log=array(tools.import_ts(path_log)[0])
## data_lin_log=merge_lin_log(data_lin, data_log, merge_at=0.1, overlap=10)
#
#ff=data_log[:,3]
#time=data_log[:,0]
#D, succes=ff_fit_Rouse_small_q (time,ff, 0.27)
#print str(D)
#
#mintime=time[1] #skip the zero
#maxtime=time[-1]
#print mintime
#print maxtime
#time_curve=logspace(log(mintime)/log(10), log(maxtime)/log(10), len(time)*30)
#
#pp.figure()
#pp.plot(data_log[::,0], data_log[::,3], 'x', label="T=1.00, q=0.27", ms=3)
#pp.plot(time_curve, exp(-1*(time_curve)*D[0]*0.27**2), label="exp(-tDq^2), D="+str(round(D[0],6)), lw=2)
#pp.xscale('log')
#pp.ylim(-0.05,1.05)
#pp.legend(loc=3)
#pp.xlabel("t",size="large")
#pp.ylabel("F(q,t)/F(q)",size="large")
#
#pp=matplotlib.backends.backend_pdf.PdfPages('/home/users/aljosha/DATA/ff01-2015.04.29/T1.00-isf-logscale/q0.27-fitted.pdf')
#pp.savefig(pp ,format="pdf")
#pp.close()
#
#pp.show()

def rescale_time_Aq4t(time, q, W, b):
    """ rescale_time_Aq4t(time, q, W, b) returns time time*q**4*W*b**4*np.pi/144 """
    return time*q**4*W*b**4*np.pi/144
#   return time*q**2*W*b**4*np.pi/144 for external length scales.

def rescale_S_qt_dRPA(time, S_qt, F_q, S_0, q, W, b):
    """ rescale_S_qt_dRPA(time, S_qt, F_q, S_0) returns a Nrows*2 numpy array with in first column a rescaled time
        using tq^4*A(W,b) and in second column a rescaled dsf using dRPA scaling S_qt*F_q/(S_0)**2 """
    time_Aq4t=rescale_time_Aq4t(time, q, W, b)
    S_qt_scaled=S_qt*F_q/(S_0**2)
    out_array=np.zeros((len(time_Aq4t), 2))
    out_array[:,0]=time_Aq4t
    out_array[:,1]=S_qt_scaled
    return out_array

def rescale_S_qt_dRPA_noS0(time, S_qt, F_q, S_q, q, W, b):
    """ rescale_S_qt_dRPA(time, S_qt, F_q, S_0) returns a Nrows*2 numpy array with in first column a rescaled time
        using tq^4*A(W,b) and in second column a rescaled dsf using dRPA scaling S_qt*F_q/(S_0)**2 """
    time_Aq4t=rescale_time_Aq4t(time, q, W, b)
    S_qt_scaled=S_qt*F_q/S_q*(1.0/S_q-1.0/F_q)

    print "For your information: S(q)^-1 - F(q)^-1 = " + str(1.0/S_q-1.0/F_q)
    
    out_array=np.zeros((len(time_Aq4t), 2))
    out_array[:,0]=time_Aq4t
    out_array[:,1]=S_qt_scaled
    return out_array

def find_isf_files(path, filehook="*5ave*", regex_2find_q="_q[\d.]*_"):
    """ def find_isf_files(path) returns list qvals with all q-values and dict{qvals, filenames} dictQ2F that turns up
    a filename for each target q-value """
    files=gl.glob(path+filehook)
    #print files
    
    try:
        idx_file2=[  [float(re.search(regex_2find_q, i).group()[2:-1]), i]  for i in files]
    except AttributeError:
        print "Caught an AttributeError: No files found in " + path + filehook + " that match regex " + regex_2find_q + "!"
        return None        
    
    dictQ2F = dict(idx_file2)
    qvals=np.sort(np.array(idx_file2)[:,0])        
    return qvals, dictQ2F
        
   
def weed_out(data, dep_col=1, threshold=0.1, weed=100):
    """
    Returns an numpy array in which every point of data is taken for rows
    with dep_col values above <threshold>, and in which every <weed>th point
    is taken for values beneath <threshold>.
    """
    #if data.shape[1] < 2:
    #    print "Can't weed on a vector, empty array or non-numpy structure"
    #    return data
        
#    split_at = index_first(data[:,dep_col], threshold)
#    N_fs = split_at # amount of samples in the full regime
#    N_tw = len(data) - split_at # amount of samples to weed
#    N_w =  int(np.floor(N_tw/weed)) # amount of weeded samples # int(floor) to cope when N_s/weed is decimal
#    
#
#    data_out=np.zeros((N_fs+N_w+1,data.shape[1]))    
#
#    
#    data_out[:N_fs]=data[:N_fs]
#    data_out[N_fs:]=data[N_fs::weed]
    
    
    mask_fullsample=(data[:,dep_col] <= threshold)
    data_out=np.vstack((data[mask_fullsample,:],data[ (mask_fullsample == False),:][::weed,:]))
    
    return data_out

class empty():
    def __getitem__(self, *args):
        return None
    #
#
def plot_series(path_series, columns=[0,1], label_series=empty(), \
output_file=None, clrs=pp.cm.gnuplot, weed_threshold=1e4, weed=1):
    """
    Plots data from text files to which path_series points. Paths are supplied
    as an iterable of strings in path_series (lists, tuples, arrays would
    work). Columns are supplied by an iterable of integers. Label_series can
    be used to supply labels, while clrs is the colormap to be used.
    """
    markers=['x','o','v','^','4','8','s','p','>','<','*','.','1','2','3']
    if label_series[0]!=None:
        path_series,label_series=sort_legend_entries((path_series,label_series))
    for i in range(0,len(path_series)):
        data=np.loadtxt(path_series[i])[:,np.array([columns[0],columns[1]])]
        data=weed_out(data, dep_col=0, threshold=weed_threshold, weed=weed)
        pp.plot(data[:,0], data[:,1], marker=markers[i%len(markers)],\
            markerfacecolor='none',\
            markeredgecolor=clrs(float(i)/len(path_series)),\
            label=label_series[i],
            color=clrs(float(i)/len(path_series)))
        pp.legend()
    #
#
def sort_legend_entries(tuple_handleslist_labelslist):
    """
    alias for your convenience: sle
    def sort_legend_entries(tuple_handleslist_labelslist) takes the 
    tuple from pyplot's axis object's get_legend_handles and sorts the handles
    with current label converted to float as key. The same procedure is 
    applied to the labels themselves. The inefficient method is chosen to 
    highlight the analogy in the syntax. This function is handy for labels
    that are numbers, but are unsorted. Use with pyplot as follows:
    ax.legend(sle.ax.get_legend_handles)
    """
    handles=tuple_handleslist_labelslist[0]
    print handles
    print handles[0]
    labels=tuple_handleslist_labelslist[1]
    handles=sorted(handles, key=lambda f: \
float(re.findall("[\.\d]+",labels[handles.index(f)])[0]))
    labels=sorted(labels, key=lambda f: \
float(re.findall("[\.\d]+", labels[labels.index(f)])[0]))
    return handles, labels
#
def rndstring(str_array, decimals=2):
    return map(str, np.around(map(float,str_array),decimals))
#
def plot_series_from_data(data_series, columns=[0,1], label_series=empty(), \
output_file=None, clrs=None):
    """
    Plots data from text files to which path_series points. Paths are supplied
    as an iterable of strings in path_series (lists, tuples, arrays would
    work). Columns are supplied by an iterable of integers. Label_series can
    be used to supply labels, while clrs is the colormap to be used.
    """
    markers=['x','o','v','^','4','8','s','p','>','<','*','.','1','2','3']
    if label_series[0]!=None:
        for i in range(0,len(data_series)):
            data=data_series[i]
            if clrs!=None:
                pp.plot(data[:,0], data[:,1], marker=markers[i%len(markers)],\
                    markerfacecolor='none',\
                    markeredgecolor=clrs(float(i)/len(data_series)),\
                    label=label_series[i],
                    color=clrs(float(i)/len(data_series)))
            if clrs==None:
                pp.plot(data[:,0], data[:,1], marker=markers[i%len(markers)],\
                    label=label_series[i], markeredgecolor='none')
            pp.legend()
        #
    #
    if label_series[0]==None:
        data=data_series[i]
        pp.plot(data[:,0], data[:,1], marker=markers[i%len(markers)],\
            label=label_series[i])
        pp.legend()
    #
#
def plot_series_from_dict(dict_q2ser, dict_q2lbl, output_file=None, clrs=None):
    markers=['o','v','^','s','p','>','<','*','.','1','2','3']
    q_sorted=sorted([q for q in dict_q2ser])
    for i in range(0,len(q_sorted)):
        data=dict_q2ser[q_sorted[i]]
        lbl=dict_q2lbl[q_sorted[i]]
        if clrs==None:
            pp.plot(data[:,0], data[:,1], marker=markers[i%len(markers)], \
                label=lbl, markeredgecolor='none')
        elif clrs!=None:
            pp.plot(data[:,0], data[:,1], marker=markers[i%len(markers)], \
                markerfacecolor='none',\
                markeredgecolor=clrs(float(i)/len(q_sorted)),\
                label=lbl,
                color=clrs(float(i)/len(q_sorted)))           
        #
    #
    pp.legend()
#
sle=sort_legend_entries
def chop_series(data, dep_col, condition=lambda f: f<0 ):
    """
    Returns only those rows in data with an index that is lower than the row
    with lowest index in which condition() is evaluated as true. Condition
    can be any method that returns a boolean, data is an iterable that supports
    [a,b]-indexing (typically a numpy array), and dep_col is the column on 
    which condition() is evaluated.
    """
    for i in range(0,len(data[:,dep_col])):
        if condition(data[i,dep_col]):
            return data[0:i,:]
        #
    #
    return data
#
def select_data(data, numbers, numbers_to_check, \
    condition=lambda f,g: f in g):
    """
    Data is an iterable, typically a list of 
    numpy arrays. The function returns a new iterable of with all members
    that have indexes idx to which condition(numbers[idx],numbers_to_check)
    evaluates to true.
    For example, numbers_to_check can be a list of known and present q-vectors,
    numbers can be a requested collection of vectors to plot, and data could
    contain the corresponding correlation functions.
    condition=True will return all members, condition=False will return 
    NoneType. condition = lambda f,g: f in g will check if f is a member of g.
    """
    out_data=[]
    numbers_accepted=[]
    for i in range(0,len(data)):
        if condition(numbers[i],numbers_to_check):
            out_data.append(data[numbers[i]])
            numbers_accepted.append(numbers[i])
            print("Found %f"%(numbers[i]))
        #
    #
    return out_data, numbers_accepted
#
def generate_dummydict(qvals, value):
    values=[ value for i in range(0, len(qvals)) ]
    return dict(zip(qvals, values))
#
def plot_F_qt_from_dir(path, mask, re_2fnd_q, qvals, w, be, wd_thr=None, \
wd=None,\
rfqt_path="/tmpmnt/home/users/aljosha/RESULTS/formfactor_Rouse_scaling_\
function.dat"):
    qvals=sorted(qvals)
    if wd==None: wd=generate_dummydict(qvals, 1)
    if wd_thr==None: wd_thr=generate_dummydict(qvals, 0)    
    #
    _,dict_q2f=find_isf_files(path, mask, re_2fnd_q)
    dict_q2ser=dict(zip(\
        qvals, [np.loadtxt(dict_q2f[q]) for q in qvals]))
    for q in dict_q2ser: # cycle through dictionary q-key and treat data
        print("Chopping and weeding q=%f \n of length %i"%(q,len(dict_q2ser[q])))
        dict_q2ser[q][:,0]=\
            rescale_time_Aq4t(dict_q2ser[q][:,0],q,w,be)
        dict_q2ser[q]=chop_series(dict_q2ser[q],3)
        print("Chopped q=%f \n of length %i"%(q,len(dict_q2ser[q])))
        dict_q2ser[q]=weed_out(dict_q2ser[q], 0, \
            wd_thr[q], wd[q] )
        dict_q2ser[q]=dict_q2ser[q][:,np.array([0,3])]
        # 
    #
    dict_q2lbl=dict(zip(qvals, ["q="+str(q) for q in rndstring(qvals)]))
    plot_series_from_dict(dict_q2ser, dict_q2lbl)
    #
    Rouse_Fqt=chop_series(fastts(rfqt_path),1,lambda f: f<1e-4)
    pp.plot(Rouse_Fqt[:,0], Rouse_Fqt[:,1], '--', \
        label="Rouse", linewidth=2, color='black')
#
def gr(array, min, max):
    """
    Gets a range to index <array>, an iterable, between numeric values closest 
    to <min> and <max>.
    """
    idx=index_nearest
    return range(idx(array,min),idx(array,max))
#
def plot_S_qt_dRPA(qfiles, realq, w, be, S_0, dsfpath, S_qpath, \
Rouse_Sqt_path, **kwargs):
    markers=['v','^','s','p','>','<','*','.','1','2','3']
    fig=pp.figure()
    ax=fig.gca()
    if "add" in kwargs:
        [ax.plot([0],[0]) for i in range(0,kwargs["add"])]
    #
    S_q=np.loadtxt(S_qpath)[:,np.array([0,3])]
    S_q=S_q[np.where(S_q[:,1]>0)]
    F_qs=[ S_q[index_nearest(S_q[:,0], q), 1] for q in realq ]
    filenames=[dsfpath+qf for qf in qfiles]
    dsfs=[ np.loadtxt(f)[:,np.array([0,1])] for f in filenames ]
    S_qts=[ rescale_S_qt_dRPA(dsfs[i][:,0], dsfs[i][:,1], F_qs[i],\
        S_0, realq[i], w, be) for i in range(0,len(realq))]
    lines=[ax.plot(S_qts[i][:,0], S_qts[i][:,1])[0] for i in range(0,len(realq))]
    [ax.plot(S_qts[i][::5,0], S_qts[i][::5,1], marker=markers[i], \
        linewidth=0, markerfacecolor=lines[i].get_color(), \
        label="q="+str(round(realq[i],2)))[0] for i in range(0,len(realq))]
    Rouse_Sqt=np.loadtxt(Rouse_Sqt_path)
    pp.plot(Rouse_Sqt[:,0], Rouse_Sqt[:,1], '--', label="Rouse dRPA", \
        linewidth=2, color='black')
    return fig
#
def gaussian_F_q(R_s_sq, chain_length, qrange=np.arange(0,50,0.1)):
    """
    Takes an numpy array R_s_sq with in the first column a monomer index and in
    the second column a mean squared average distance divided by the monomer
    index, an integer chain_length, and, optionally, qrange, a numpy array. 
    Calucalates F_q under the Gaussian assumption, namely that the scattering
    can be described by the averages of the separations, absolving the necessity
    of weighing all measured separations. Returns two lists (qrange, Gaussian_F_qs)
    as one tuple, with the calculated F_q as function of q.
    """
    terms=[ [] for q in qrange ]
    Gaussian_F_qs=[ [] for q in qrange ]
    for q_idx in range(0,len(qrange)):
        for i in range(1, chain_length + 1):
            for j in range(1, chain_length + 1):
                s=abs(i-j)
                if s>0:
                    current_R_s_sq=R_s_sq[index_nearest(R_s_sq[:,0], s), 1]*s
                    term=np.exp(-1./6*qrange[q_idx]**2*current_R_s_sq)
                elif s==0:
                    term=1
                terms[q_idx].append(term)
            #
        #
        Gaussian_F_qs[q_idx]=sum(terms[q_idx])/chain_length
    #
    return (qrange, Gaussian_F_qs)
#
def main(*args):
    print("Use 'import tools' to harness the power of tools.py\n\
<3 Aljosha")
#
if __name__ == '__main__':
    main(sys.argv)                                    # update to accomodate for more command line arguments
#