#!/usr/bin/perl
#########################################
#	- Prepare the input files for a fit by gnuplot on the distribution
#	   of relaxation times provided by CONTIN
#	- Fit the distribution
# - Skip the fits for some cases and label these ones
#	- Format the fit results for the peaks of the distribution
#	- Write a .txt file with the results for further use
#	- Plot the distribution with fitting curves
#
#	FS  last modif 2013/12/29
#########################################

chop($p = `pwd`); $path = ($ARGV[0] eq "" ? $p : $ARGV[0]);

$xmin = $xmax = 0;
$l10 = log(10);
$max_error = 200; 																# max % error on fitting parameters
opendir(DIR,$path); @allfiles = readdir(DIR); closedir(DIR);

# remove TMP_LOG if present
system("rm -f $path/TMP_LOG");

# if batch mode check existence of file INFO_F in directory
if ( $ARGV[0] ) { @files = grep (/INFO_F/, @allfiles);}

# if INFO_F not present or interactive mode,  get info & create INFO_F 
if (@files == 0) { &get_INFO_F;}

# read INFO_F, create TMP_PARAM & TMP_FITFCT
&read_INFO_F;

# fit distribution and check criteria on results
unless ($miss) {																	# unless not the number of peaks requested by user
	&output_fit;																	# make gnuplot file to fit time distribution
	system("gnuplot $path/TMP_FIT");									# execute gnuplot file
	if ($ARGV[0]) { &check_fit;}											# check fit quality
}

# output fit results
&read_info;																		# get useful info stored for gnuplot in TMP_PLOTVAR
&read_param_new;																# get final values of fit parameters
&get_avrg_int;																	# get average intensity value
&read_distrib;																	# get g(0) and asymptote fitted values
&output_fit_txt;																# write final values to "filename_fit.txt"
&plot;																				# define content of plot depending on fit quality
&output_fitplot;																	# make gnuplot file to plot time distribution and its fit
system("gnuplot $path/TMP_FITPLOT");								# execute gnuplot file												

########################################
# get the input parameters to fit the peaks of the distribution
sub get_INFO_F {
	print "Number of log-normal peaks ? (return to skip and use values in file INFO_F) ";
	chop($p=<STDIN>);
	if ($p ne "") {																	# to skip this step in interactive mode if INFO_F exists and was updated manually
		$i = 1;																		# else enter values in line
		print "\nAutomatic initial trial values ? y (default) or n\n";
		chop($a = <STDIN>);
		if ($a eq "n") {
			print "\nEnter initial trial values\n";
			while ($i<=$p) {
				print "Amplitude pic ",$i," ? ";
				chop($t=<STDIN>);
				$a[$i] = $t;
				print "log [peak ",$i," position (s)] ? ";
				chop($t=<STDIN>);
				$pos[$i] = $t;
				print "log [peak ",$i," width] ? ";
				chop($t=<STDIN>);
				$lp[$i] = $t;
				$i++;
			}
		}
		print "start of fitting region (log) (s) ? ";
		chop($xmin=<STDIN>);
		print "end of fitting region (log) (s) ? ";
		chop($xmax=<STDIN>);
		&output_INFO_F;
	}
}
########################################
# create INFO_F
sub output_INFO_F {
	$i=1;
	open (OUT,">$path/INFO_F") || die "cannot create $path/INFO_F";
	print OUT $p,"\n";
	print OUT $xmin,"\n";
	print OUT $xmax,"\n";
	while ($i <= $p) {
		print OUT qq(a$i=$a[$i]\n);
		print OUT qq(b$i=$pos[$i]\n);		
		print OUT qq(c$i=$lp[$i]\n);
		$i++;
	}
	close(OUT);
}
########################################
# read the initial parameters of the fit from INFO_F
sub read_INFO_F {
	open (IN,"<$path/INFO_F") || die "cannot open $path/INFO_F";
	chop($p = <IN>);
	chop($xmin = <IN>);
	chop($xmax = <IN>);
	chop($firstentry = <IN>);
	if ($firstentry eq "a1=" || $firstentry eq "") {
		&get_distr;
		&findpeaks;
		&param;
	} else {
		open (OUT,">$path/TMP_PARAM") || die "cannot create $path/TMP_PARAM";
		print OUT $firstentry,"\n";
		while (<IN>) {print OUT;}
		close(OUT);
	}			
	close(IN);
}
########################################
# get distribution data from TMP_DISTRIB
sub get_distr {
	open(IN, "<$path/TMP_DISTRIB") || die "cannot open $path/TMP_DISTRIB ! ";
	$i = 0;
	while ($i < 10) {
		chop($head[$i] = <IN>);
		$i++;
	}
	$i = 0;
	while (<IN>) {
		chop($tmp[$i] = $_);
		$i++;
	}
	close(IN);
}
#######################################
# calculate second derivative and transform it to find peaks
sub findpeaks {
# extract x,y distribution values 	
	$j = 0;
	while ($j<= $#tmp) {
		@tamp = split(/\t/,$tmp[$j]);
		$x[$j] = $tamp[5];
		$y[$j] = $tamp[1];
		$j++;
	}
# calculate approx second derivative up to a numerical cst
	$j = 2;
	while ($j <= $#tmp-2) {
		$sd[$j] = -2*$y[$j-2]+32*$y[$j-1]-60*$y[$j]+32*$y[$j+1]-2*$y[$j+2];
		$j++;
	}
# set positive values to zero and negative ones to positive 
	$j = 2;
	while ($j <= $#tmp-2) {
		$sd[$j] = ($sd[$j] < 0 ? -$sd[$j] : 0);
		$j++;
	}
# remove isolated spikes
	$j = 2;
	while ($j <= $#tmp-2) {
		if (($sd[$j-1] == 0) && ($sd[$j+1] == 0)) {$sd[$j] = 0;}
		$j++;
	}
# restrict examination at ROI [xmin,xmax] set in INFO_F
	$jmin = $jmax = $j = 2;
	while ($j <= $#tmp-2) {
		$jmin = ($x[$j] >= $xmin ? $jmin : $j);
		$jmax = ($x[$j] >= $xmax ? $jmax : $j);
		$j++;
	}
	$j = $jmin;
	$k = 0;
# obtain boundaries of remaining peaks
	while ($j <= $jmax) {
		if ((($sd[$j] == 0) && ($sd[$j+1] !=0)) || (($sd[$j-1] != 0) && ($sd[$j] ==0))) {
			$pb[$k] = $j;
			$k++;
		}
	$j++;
	}
# obtain peak amplitude, position, and width	
	$k = 0;
	$maxarea = 0;
	for ($j = 0; $j < ($#pb+1)/2; $j++) {
		$max = $pb[2*$j];
		for ($k = $pb[2*$j]; $k <= $pb[2*$j+1];$k++) {
			$max = ($sd[$max] > $sd[$k] ? $max : $k);
		}
		$ap[$j+1] = $y[$max];																		# amplitude (index set to 1 for peak 1 !)
		$posp[$j+1] = $x[$max];																	# position
		$lpp[$j+1] = ($x[$pb[2*$j+1]]-$x[$pb[2*$j]])/2;								# width
		$s{$j+1} = $ap[$j+1]*$lpp[$j+1];														# approximate area
		$maxarea = ($s{$j+1} > $maxarea ? $s{$j+1} : $maxarea);					# get max approximate area
	}
# select peaks according to the input value of $p
	if ($p < 1) {																							# search for both peak number and positions
		$p = ($p == 0 ? 0.01 : $p);																	# based on area relative to largest one
		$critarea = $p*$maxarea;																# use $p as criterion. If null, set it arbitrarily.
		$k = 1;
		for ($j = 1 ; $j <= ($#pb+1)/2 ; $j++) {
			if ($s{$j} > $critarea) {																# discard too small peaks based on area relative to largest one
				$temp{$posp[$j]} = join("\t",($ap[$j],$posp[$j],$lpp[$j]));
#				$a[$k] = $ap[$j];
#				$pos[$k] = $posp[$j];
#				$lp[$k] = $lpp[$j];
				$k++;
			}
		}
		$p = $k-1;																						# update number of peaks
	} else {																								# fixed number of peaks, search only for positions of $p largest peaks
		$k  = 1;
		foreach $key (sort {$s{$b} <=> $s{$a}} keys %s) {
			if ($k <= $p) {
				$temp{$posp[$key]} = join("\t",($ap[$key],$posp[$key],$lpp[$key]));
				print OUT $temp{$posp[$key]},"\n";
				$k++;
			}
		}
	}
	# reorder selected peaks according to increasing times
	$k = 1;
	foreach $key (sort {$a <=> $b} keys %temp) {
		if ($k <= $p) { ($a[$k], $pos[$k], $lp[$k]) = split(/\t/,$temp{$key});	$k++;}
	}
	if ($k == $p) { $miss = 1;}																		# check consistency between searched for and found number of peaks
}
########################################
# build the initial parameters of the fit
# output in TMP_PARAM for further use by gnuplot
sub param {
	$i = 1;
	open(OUT, ">$path/TMP_PARAM") || die "cannot create $path/TMP_PARAM ! ";
	while ($i <= $p) {
		print OUT qq(a$i=$a[$i]\n);
		print OUT qq(b$i=$pos[$i]\n);		
		print OUT qq(c$i=$lp[$i]\n);
		$i++;
	}
	close(OUT);
}
########################################
#	create gnuplot file TMP_FIT to:
#			show CONTIN distribution TMP_DISTRIB
#			fit the peaks of the distribution
#			display the results on screen if single file interacting mode
sub output_fit {
	open(OUT,">$path/TMP_FIT");
	print OUT qq(set loadpath "$path"\n);
	print OUT qq(set termoption enhanced\n);
	print OUT qq(set sample 512\n);
	print OUT qq(load "TMP_PLOTVAR"\n);
	print OUT qq(set nolabel\n\n);
	#	set fit parameters
	&fct;																													#	fit function f(x)
	print OUT qq(load "TMP_PARAM"\n);																	#	starting values for the parameters
	# plot distribution & initial values of the fit function f(x)
	print OUT qq(set xrange [xmin:xmax]\n);
	print OUT qq(set x2range [log10(xmin):log10(xmax)]\n);
	print OUT qq(set yrange [0:*]\n\n);
	print OUT qq(set logscale x\n\n);
	print OUT qq(set grid\n);
	print OUT qq(set xtics 10 format "10^{%T}" font "Helvetica,18"\n);
	print OUT qq(set nomxtics\n);
	print OUT qq(set ytics nomirror font "Helvetica,18"\n\n);
	print OUT qq(set xlabel "time (s)" font "Helvetica,24"\n);
	print OUT qq(set ylabel "amplitude" font "Helvetica,24"\n);
	print OUT qq(set x2label "   "\n);
	print OUT qq(set y2label "   "\n\n);
	if (!$ARGV[0]) {																									# screen display for interactive mode
		print OUT qq(plot "TMP_DISTRIB" using 1:2:3 title "distribution" with errorbars pt 7 ps 1.5, f(x) axes x2y1 with lines lc 0 lw 1.5; pause mouse any\n);
	}
	#	fit distribution & display it again with final values of the fits
	print OUT qq(FIT_MAXITER = 40\n) if ( $ARGV[0] );											# set max number of iterations for batch mode
	print OUT qq(set fit logfile "$path/TMP_LOG"\n);
	print OUT qq(fit [xfitmin:xfitmax] f(x) "TMP_DISTRIB" using 6:2 via "TMP_PARAM"\n);
	print OUT qq(update "TMP_PARAM" "$path/TMP_PARAM_NEW"\n);						#	store final values in TMP_PARAM_NEW
	if (!$ARGV[0]) {																									# screen display for interactive mode
		print OUT qq(plot "TMP_DISTRIB" using 1:2:3 title "distribution" with errorbars pt 7 ps 1.5, f(x) axes x2y1 with lines lc 0 lw 1.5; pause mouse any\n);
	}
	close(OUT);
}
########################################
# build the f(x) string with $p peaks of log-normal distributions
# output in TMP_FITFCT together with fit limits for further use by gnuplot ----------------------------
sub fct {
	$i = 1;
	$funct[0]="f(x)=";
	while ($i <= $p) {
		$funct[0].="a".$i."*exp(-((x-b".$i.")/c".$i.")**2)+";
		$funct[$i]="f".$i."(x)=a".$i."*exp(-((x-b".$i.")/c".$i.")**2)";
		$i++;
	}
	chop $funct[0];
	print OUT qq($funct[0]\n);
	if ($p > 1) {
		$i=1;
		while ($i <= $p) {
			print OUT qq($funct[$i]\n);
			$i++;
		}
	}
	print OUT qq(npics=$p\n);
	print OUT qq(xfitmin=$xmin\n);
	print OUT qq(xfitmax=$xmax\n);
}
########################################
# check fit quality
sub check_fit {
	open(IN,"<$path/TMP_LOG");
	while (<IN>) {
		if (/iterations/) { 
			@temp = split(/ /);
			if ($temp[1] > 30) { $slow_conv = 1;}
		}
		if (/Maximum iteration count/) { $slow_conv = 1;}
		if (/\((.*%)/) { 
			$error = $1; 
			$error =~ s/%//; 
			if ($error > $max_error) { $large_error = 1;}
			if (/a\d/) {  
				@temp = split(/ [ ]*/); 
				if ($temp[2] <= 0) { $unphysical = 1;}
			}
		}
	}
	close(IN);
}
########################################
# get useful info stored initially for gnuplot
sub read_info {
	open(IN, "<$path/TMP_PLOTVAR") || die "cannot open $path/TMP_PLOTVAR ! ";
	chop($tmp=<IN>);
	@name=split(/"/,$tmp);
	chop($tmp=<IN>);
	chop($tmp=<IN>);
	chop($tmp=<IN>);
	@cst=split(/ /,$tmp);
	chop($tmp=<IN>);
	@max=split(/ /,$tmp);
	close(IN);
}
########################################
# get final values of fit parameters
sub read_param_new {
# first check if TMP_PARAM_NEW present. If absent fit had a BREAK. Then simply use initial parameter values
	opendir(DIR,$path);
	if ( !grep (/PARAM_NEW/, readdir(DIR))) { 
		system("cp $path/TMP_PARAM $path/TMP_PARAM_NEW");
		$break = 1;
	}
	closedir(DIR);
# read TMP_PARAM_NEW whatever it contains 
	$i=1;
	open(IN, "<$path/TMP_PARAM_NEW");
	while (<IN>) {
		chop; @temp = split(/=/);
		$t[$i] = $temp[$#temp];
		$i++;
	}
	close(IN);
}
########################################
# read CONTIN input file
sub get_avrg_int {
	if ($ARGV[1]) {									# batch mode: $Im and $dIm passed in a string
		@tmp = split(/ /,$ARGV[1]);
		$Im = $tmp[2];
		$dIm = $tmp[4];
	} else {												# interactive mode: read again $Im and $dIm
		open(DATA, "<$path/$name[1]") || die "cannot open $path/$name[1] ! \n";
		while (<DATA>) {
			s/\r//;			# deletes CR !
			s/\n//;			# deletes LF !
			
			if (/RUSER    25/) { 
				@tmp = split(/ [ ]*/);
				$Im = $tmp[3];
			}
			
			if (/RUSER    26/) {
				@tmp = split(/ [ ]*/);
				$dIm = $tmp[3];
			}
		}
		close (DATA);
	}
}
########################################
# read distribution data
sub read_distrib {
	open(RESULT, "<$path/TMP_DISTRIB") || die "cannot open $path/TMP_DISTRIB ! \n";
	
# skip first 6 lines
	$i = 0;
	while ($i < 6) {
		$item=<RESULT>;
		$i++;
	}
# then read useful info
	$asympt=<RESULT>;
	$Tmax=<RESULT>;
	$Rmax=<RESULT>;
	
# then read distribution data
	$i = 0;
	while (<RESULT>) {
		chop;
		($abscissa[$i], $ordinate[$i], $error[$i]) = split(/\t/);
		$i++;
	}
	close (RESULT);
	$max = $i-1;															# nb. of grid points

	$cum = 0;
	$i = 0;
	while ($i++ < $max) {
		$cum += $ordinate[$i];
	}
}
########################################
# write gnuplot file TMP_FITPLOT to plot fitted distribution 
#		if single file interacting mode display CONTIN distribution TMP_DISTRIB
#		together with the fit of the peaks and the values of the parameters
#		output to .eps file
sub output_fitplot {
	open(OUT,">$path/TMP_FITPLOT");
	print OUT qq(set loadpath "$path"\n);
	print OUT qq(set termoption enhanced\n);
	print OUT qq(set sample 512\n);
	print OUT qq(load "TMP_PLOTVAR"\n);
	print OUT qq(set nolabel\n);
	&plotlabels;
	print OUT qq(set xrange [xmin:xmax]\n);
	print OUT qq(set x2range [log10(xmin):log10(xmax)]\n);
	print OUT qq(set yrange [0:*]\n);
	print OUT qq(set logscale x\n);
	print OUT qq(set grid\n);
	print OUT qq(set xtics 10 format "10^{%T}" nomirror font "Helvetica,18"\n);
	print OUT qq(set nomxtics\n);
	print OUT qq(set ytics nomirror font "Helvetica,18"\n);
	print OUT qq(set xlabel "time (s)" font "Helvetica,24"\n);
	print OUT qq(set ylabel "amplitude" font "Helvetica,24"\n);
	print OUT qq(set x2label "   "\n);
	print OUT qq(set y2label "   "\n);
	print OUT qq(unset grid\n);
	if (!$ARGV[0]) { print OUT qq($plot; pause mouse any\n);}				# screen display if interactive mode
	#	output previous one to .eps file
	print OUT qq(set terminal postscript eps enhanced\n);
	print OUT qq(set output "$path/TMP_FIT.eps"\n);
	print OUT qq(unset grid\n);
	print OUT qq($plot\n);
	print OUT qq(set term pop\n);
}
########################################
# produce labels with results for gnuplot
sub plotlabels {
	if ($miss) {
		print OUT qq(set label "X" font "Monaco,108" tc rgb "#FF00FF" at screen 0.8,0.7\n);		# label with a magenta X
		print OUT qq(set label "Wrong NUMBER of peaks" font "Helvetica,30" at graph 0.05, 0.95\n);
	} elsif ($unphysical) {
		print OUT qq(set label "X" font "Monaco,108" tc rgb "#FF0000" at screen 0.8,0.7\n);		# label with a red X
		print OUT qq(set label "UNPHYSICAL amplitude value" font "Helvetica,30" at graph 0.05, 0.95\n);
	} elsif ($large_error) {
		print OUT qq(set label "X" font "Monaco,108" tc rgb "#FF9999" at screen 0.8,0.7\n);		# label with a pale red X
		print OUT qq(set label "Too LARGE ERROR in parameters" font "Helvetica,30" at graph 0.05, 0.95\n);
	} elsif ($slow_conv) {		
		print OUT qq(set label "X" font "Monaco,108" tc rgb "#FF9900" at screen 0.8,0.7\n);		# label with a orange X
		print OUT qq(set label "Too SLOW fit convergence" font "Helvetica,30" at graph 0.05, 0.95\n);
	} elsif ($break) {
		print OUT qq(set label "X" font "Monaco,108" tc rgb "#0000FF" at screen 0.8,0.7\n);		# label with a blue X
		print OUT qq(set label "BREAK during fit" font "Helvetica,30" at graph 0.05, 0.95 -($i+2)*0.06\n);
	} else {
		print OUT qq(load "TMP_PARAM_NEW"\n);
		&fct;
		$np = (@t-1)/3;						# nb of peaks
		$i = 1;
		print OUT qq(set label "{P}_{p} = $Tmax s : $Rmax nm" at graph 0.05, 0.95\n);
		while ($i <= $np) {
			$ii=3*($i-1)+2;
			print OUT qq(set label "{P}_{$i} = $T[$ii] s : $R[$ii] nm" at graph 0.05, 0.95-$i*0.06\n);
			$i++;
		}
	}
}
########################################
# produce plot instructions for gnuplot
sub plot {
	$plot=qq(plot "TMP_DISTRIB" using 1:2:3 title "distribution" with errorbars pt 7 lc 1 ps 1.5);
	unless ($miss || $unphysical || $slow_conv || $large_error || $break) {
		$plot .= qq(, f(x) axes x2y1 with lines lt 1 lc 0 lw 2);
		if ($np > 1) {
			$i=1;
			while ($i <= $np) {
				$plot.=qq(, f).$i.qq((x) axes x2y1 with lines lc 0 lw 2);
				$i++;
			}
		}
	}
}
########################################
# write fit results to "filename_fit.txt"
sub output_fit_txt {
	open(OUT, ">$path/$name[1]_fit.txt") || die "cannot create $path/$name[1]_fit.txt ! ";
	$i = 1;
# mark for fit quality, if not OK return
	if ($miss) { 
		print OUT "Wrong NUMBER of peaks\n"; close(OUT); return;
	} elsif ($unphysical) {
		print OUT "UNPHYSICAL amplitude value\n"; close(OUT); return;
	} elsif ($large_error) {
		print OUT "Too LARGE ERROR in parameters\n"; close(OUT); return;
	} elsif ($slow_conv) {
		print OUT "Too SLOW fit convergence\n"; close(OUT); return;
	} elsif ($break) {
		print OUT "BREAK during fit\n"; close(OUT); return;
	} else {
		print OUT "OK\n";
	}

	&read_TMP_LOG;
# output formatted results to *_fit.txt
	$j = 1;
	print OUT @name[1]," time(s) radius(nm)\n";
	$Tmax = sprintf("%1.2e",$max[2]);
	$Rmax = sprintf("%1.2e",$cst[2]*$max[2]);
	print OUT "Max ",$Tmax," ",$Rmax,"\n";
	while ($i < @tl) {
		if ($i % 3 == 2) {
			$et = "pos.";
			$T[$i] = sprintf ("%1.3e",10**$tl[$i]);
			$dT[$i] = sprintf ("%1.2e",abs(10**$tl[$i]*$l10*$error[$i]/100*$tl[$i]));					# @error = relative error in % !!!
			$R[$i] = sprintf ("%1.3e",$T[$i]*$cst[2]);
			$dR[$i] = sprintf ("%1.2e",$dT[$i]*$cst[2]);
			print OUT $et," ",$T[$i]," +/- ",$dT[$i]," ",$R[$i]," +/- ",$dR[$i],"\n";
		} else {
			if ($i % 3 == 1) { 	$np = ($i-1)/3+1; $et = "peak $np\nampl.";}
			if ($i % 3 == 0) { $et = "width";}
			$T[$i] = sprintf ("%1.2e",$tl[$i]);
			$dT[$i] = sprintf ("%1.2e",abs($tl[$i]*$error[$i]/100));
			print OUT $et," ",$T[$i]," +/- ",$dT[$i],"\n";
		}
		if ($i % 3 == 0) { 
			$aire[$j] = sprintf("%1.3e",$tl[$i-2]*abs($tl[$i])*sqrt(3.14159));
			$da = $error[$i-2] ; $dw = $error[$i];																	# @error = relative error in % !!!
			$daire[$j] = sqrt($da**2 + $dw**2 + 2*$corr_aw[$j]*$da*$dw)/100*$aire[$j];
			$daire[$j] = sprintf("%1.3e",$daire[$j]);
			print OUT "area ",$aire[$j]," +/- ",$daire[$j],"\n";
			$j++;
		}
		$i++;
	}
	$j = 1;
	while ($j <= $#aire) { $aire_tot += $aire[$j]; $daire_tot += $daire[$j]; $j++;}
	$j = 1;
	while ($j <= $#aire) { 
		$daire[$j] = sprintf("%1.3e",($daire[$j]/$aire[$j] + $daire_tot/$aire_tot)*$aire[$j]/$aire_tot);
		$aire[$j] = sprintf("%1.3e",$aire[$j]/$aire_tot);
		print OUT "peak $j % ",$aire[$j]," +/- ",$daire[$j],"\n";$j++;
	}
	print OUT "Iav ",sprintf("%1.3e",$Im),"\n";
	print OUT "dIm ",sprintf("%1.3e",$dIm),"\n";
	print OUT "g0 ",sprintf("%1.3f",$cum),"\n";
	$asympt =~ s/asymptote = //;
	print OUT "asymptote ",substr($asympt,1),"\n";
	close (OUT);	
}
########################################
# read the content of TMP_LOG
sub read_TMP_LOG {
	open(IN,"<$path/TMP_LOG");
	$k = 0;
	while (<IN>) {
		if (/\((.*%)/) { 
			$k++;
			$error[$k] = $1; 
			$error[$k] =~ s/%//;
			s/ //g;
			@tmp = split(/\+\/-/);
			@tmp = split(/=/, $tmp[0]);
			$tl[$k] = $tmp[1];
		}
		if (/correlation matrix of the fit parameters:/) { $corrmat = 1; $j = -3;}
		if ($corrmat) {
			$j++;
			if ($j >= 1) {
				chop($corr[$j] = $_);
				$corr[$j] =~ s/ [ ]*/ /g;
				$corr[$j] =~ s/^[a-c]\d //;
			}
		}
	}
	close(IN);
	$Npeak = $j /3;
	for ($k = 1; $k <= $Npeak; $k++) {
		@corrij = split(/ /,$corr[3*$k]);
		$corr_aw[$k] = $corrij[3*($k - 1)];
	}
}